-- SQLite
-- CREATE TABLE "archived_stats" ("id" integer primary key autoincrement,"device_id" integer,"download" integer,"upload" integer,"timestamp" integer)
-- CREATE TABLE "stats" ("id" integer primary key autoincrement, "device_id" integer, "download" integer, "upload" integer, "timestamp" integer)
-- CREATE TABLE "devices" ("id" integer primary key autoincrement, "mac" text, "name" text)